### PR TITLE
Fix exception in repositories with commits containing ':::' in commit message

### PR DESCRIPTION
**Pull request by mb**
Setting [maxsplit](https://docs.python.org/3/library/stdtypes.html#str.split).

The following exception was thrown:

```
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 76, in _worker_function
    task = self._task_queue.get(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 81, in _worker_function
    self.handle_maintenance(context)
  File "/home/user/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/task_queue.py", line 50, in handle_maintenance
    remaining_chunks_to_analyze = context["seagoat_engine"].analyze_codebase(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 82, in analyze_codebase
    self.repository.analyze_files()
  File "/home/user/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/repository.py", line 46, in analyze_files
    current_commit_info = parse_commit_info(line)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/repository.py", line 12, in parse_commit_info
    commit_hash, date_str, author, commit_subject = raw_line.split(":::")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)
```

### CODE REVIEW

**Comment by kantord** [comment]
Hi @mb could you please add a test case that verifies this? I think this test case could be a good inspiration for everything you need:

https://github.com/kantord/SeaGOAT/blob/8036d8c5f0f27624b3e1b4bf145c2c3aa686d615/tests/test_repository.py#L63-L82

pretty much it's enough to change it so that it adds one commit message that currently breaks due to `:::` being in the commit message. and putting `seagoat.analyze_codebase() ` at the end. that should give you a test failure if you temporarily remove your fix. an explicit assertion might not be required for this test. or you can even change an existing test case to include a commit like this

**Review by kantord — APPROVED** [review]
thanks, looks good to me now, I can merge it once the CI passes

**Comment by kantord** [comment]
there are some lint failures, probably you can fix them by running `poetry run pre-commit run --all-files` if you don't want to manually format the files 

also I see failures like this:

```

=================================== FAILURES ===================================
________________ test_commit_messages_with_three_or_more_colons ________________

repo = <tests.conftest.MockRepo '/tmp/tmphppqsmqc/.git'>

    def test_commit_messages_with_three_or_more_colons(repo):
        seagoat = Engine(repo.working_dir)
        commit_messages = {}
        for i in range(5):
            message = "add my file" + ":"*i + "!"
>           commit_messages.add(message)
E           AttributeError: 'dict' object has no attribute 'add'
```

**Comment by mb** [comment]
Unfortunatly I can't run the tests locally before/after due to errors in poetry install and therefore I cant run the tests with `poetry run pytest`. I have never used poetry before and haven't figured out yet how to resolve that.

```
Installing dependencies from lock file

Package operations: 32 installs, 0 updates, 0 removals

  • Installing docopt (0.6.2): Failed

  TypeError

  Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable

  at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
      105│     ) -> Path:
      106│         from subprocess import CalledProcessError
      107│ 
      108│         with ephemeral_environment(self._env.python) as venv:
    → 109│             env = IsolatedEnv(venv, self._pool)
      110│             builder = ProjectBuilder(
      111│                 directory,
      112│                 python_executable=env.executable,
      113│                 scripts_dir=env.scripts_dir,

  • Installing paginate (0.5.6): Failed

  TypeError

  Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable

  at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
      105│     ) -> Path:
      106│         from subprocess import CalledProcessError
      107│ 
      108│         with ephemeral_environment(self._env.python) as venv:
    → 109│             env = IsolatedEnv(venv, self._pool)
      110│             builder = ProjectBuilder(
      111│                 directory,
      112│                 python_executable=env.executable,
      113│                 scripts_dir=env.scripts_dir,

  • Installing pypika (0.48.9): Failed

  TypeError

  Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable

  at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
      105│     ) -> Path:
      106│         from subprocess import CalledProcessError
      107│ 
      108│         with ephemeral_environment(self._env.python) as venv:
    → 109│             env = IsolatedEnv(venv, self._pool)
      110│             builder = ProjectBuilder(
      111│                 directory,
      112│                 python_executable=env.executable,
      113│                 scripts_dir=env.scripts_dir,
```

**Comment by kantord** [comment]
> Unfortunatly I can't run the tests locally before/after due to errors in `poetry install` and therefore I cant run the tests with `poetry run pytest`. I have never used poetry before and haven't figured out yet how to resolve that.
> 
> ```
> Installing dependencies from lock file
> 
> Package operations: 32 installs, 0 updates, 0 removals
> 
>   • Installing docopt (0.6.2): Failed
> 
>   TypeError
> 
>   Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable
> 
>   at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
>       105│     ) -> Path:
>       106│         from subprocess import CalledProcessError
>       107│ 
>       108│         with ephemeral_environment(self._env.python) as venv:
>     → 109│             env = IsolatedEnv(venv, self._pool)
>       110│             builder = ProjectBuilder(
>       111│                 directory,
>       112│                 python_executable=env.executable,
>       113│                 scripts_dir=env.scripts_dir,
> 
>   • Installing paginate (0.5.6): Failed
> 
>   TypeError
> 
>   Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable
> 
>   at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
>       105│     ) -> Path:
>       106│         from subprocess import CalledProcessError
>       107│ 
>       108│         with ephemeral_environment(self._env.python) as venv:
>     → 109│             env = IsolatedEnv(venv, self._pool)
>       110│             builder = ProjectBuilder(
>       111│                 directory,
>       112│                 python_executable=env.executable,
>       113│                 scripts_dir=env.scripts_dir,
> 
>   • Installing pypika (0.48.9): Failed
> 
>   TypeError
> 
>   Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable
> 
>   at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
>       105│     ) -> Path:
>       106│         from subprocess import CalledProcessError
>       107│ 
>       108│         with ephemeral_environment(self._env.python) as venv:
>     → 109│             env = IsolatedEnv(venv, self._pool)
>       110│             builder = ProjectBuilder(
>       111│                 directory,
>       112│                 python_executable=env.executable,
>       113│                 scripts_dir=env.scripts_dir,
> ```

this is weird, seems like a bug in poetry itself maybe? :thinking: based on the path it seems like you have Python 3.11 and Linux though :thinking:

**Comment by kantord** [comment]
one workaroudn could be to build your own virtualenv manually, I think you can create a requirements.txt like this: 

```bash
 poetry export -f requirements.txt
```

then you should be able to create a virtualenv the old fashioned way :thinking:

**Comment by kantord** [comment]
Hi @mb I pushed a fix, I'll merge it! Thank you for the contribution

**Comment by kantord** [comment]
It will be automatically released in a couple minutes

**Comment by mb** [comment]
Thanks for doing the last steps for me

**Pull request merged**
